# Generated by Django 4.0 on 2022-07-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('contact_person_name', models.CharField(max_length=50)),
            ],
        ),
    ]
