# Generated by Django 4.0 on 2022-07-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_product_id_type_producttransaction_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
